import { Question } from './models/question.model';

export const Questions: Question[] = [
  {
  	id: 11,
  	text: 'Who are you?',
  	type: 'radio',
  	formId: 11,
  	themeId: null,
  	required: true,
    position: 1,
  },
  {
  	id: 12,
  	text: 'What is your name?',
  	type: 'radio',
  	formId: 11,
  	themeId: null,
  	required: true,
    position: 2,
  },
  {
  	id: 13,
  	text: 'How are you?',
  	type: 'text',
  	formId: 11,
  	themeId: null,
  	required: false,
    position: 3,
  },
  {
  	id: 14,
  	text: 'Where have you been?',
  	type: 'checkbox',
  	formId: 11,
  	themeId: null,
  	required: false,
    position: 4,
  },
  {
  	id: 15,
  	text: 'This is a theme question',
  	type: 'checkbox',
  	formId: null,
  	themeId: 11,
  	required: false,
    position: 1,
  },
  {
  	id: 16,
  	text: 'And this',
  	type: 'radio',
  	formId: null,
  	themeId: 11,
  	required: false,
    position: 2,
  },
  {
    id: 17,
    text: 'Who are you?',
    type: 'radio',
    formId: 13,
    themeId: null,
    required: true,
    position: 1,
  },
  {
    id: 18,
    text: 'What is your name?',
    type: 'radio',
    formId: 13,
    themeId: null,
    required: true,
    position: 3,
  },
  {
    id: 19,
    text: 'How are you?',
    type: 'text',
    formId: 13,
    themeId: null,
    required: false,
    position: 2,
  },
];
